name: client_backoffice
description: A sample command-line application.
publish_to: none
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.0
# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  lenra_components:
    git:
      url: https://github.com/lenra-io/lenra_components.git
      ref: v1.0.0-beta.52
  client_common:
    git:
      url: https://github.com/lenra-io/client-common.git
      ref: v1.0.0-alpha.1
  url_launcher: ^6.1.2
  # intl: ^0.18.0
  logging: ^1.0.2
  provider: ^6.0.1
  sentry_flutter: ^7.9.0
  go_router: ^6.0.1
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git
      ref: ae44d0bbce00c3801629b65f60783d15184a7f8f
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
flutter_icons:
  # Android
  android: true
  image_path: "assets/images/icon-512.png"
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/maskable-icon.png"
  # IOS
  ios: true
  image_path_ios: "assets/images/icon-1024-white-bg.png"
  remove_alpha_ios: true
  # Web
  web:
    generate: true
    image_path: "assets/images/icon-512.png"
  # Windows
  windows:
    generate: true
    image_path: "assets/images/icon-512.png"
  # MacOS
  macos:
    generate: true
    image_path: "assets/images/icon-512.png"
